server:
  port: 9000
  
spring:
  zipkin:
    baseUrl: http://10.10.30.159:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

  redis:
    host: redislogin.ci.sanduspace.com
    port: 33436
    password: sanduspace

zuul:
  ignoredServices: '*'
  
  routes:
    pay-route:
      service-id: sandu-cloud-pay-service 
      path: /v1/pay/**
      stripPrefix: false
      sensitiveHeaders:
    user_route:
      service-id: sandu-cloud-user-service 
      path: /v1/user/**
      stripPrefix: false
      sensitiveHeaders:
    oauth2_route:
      service-id: sandu-cloud-oauth2
      path: /v1/oauth2/**
      stripPrefix: false
      sensitiveHeaders:  
    act_route:
      service-id: sandu-cloud-activity-service 
      path: /v1/act/**
      stripPrefix: false
      sensitiveHeaders:  
      
  semaphore:
    max-semaphores: 100  #信号量隔离最大线程数,默认100

ribbon:
  ConnectTimeout: 500
  ReadTimeout: 10000
    
execution:
  isolation:
    strategy: SEMAPHORE
    thread:
      timeoutInMilliseconds: 10000   

      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


    

  