server:
  port: 8004
  error:
    include-exception: true  
spring:
  datasource:
    url: jdbc:mysql://db.mysql.ci.sanduspace.com/app_online_30?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: user_dep
    password: ?,iN%er(/8ZEr<*nNX11
  rabbitmq:
    host: 10.10.30.134
    port: 5672
    username: admin
    password: 123456abc
  zipkin:
    baseUrl: http://10.10.30.159:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  aop:
    auto: true      

  redis:
    host: redislogin.ci.sanduspace.com
    port: 33436
    password: sanduspace
        


feign:
  hystrix:
    enabled: false

    
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 6000

# logging.file: d:/zz/z.log
# logging.file.max-size: 10MB
logging:
  level:
    root: INFO
    com.ibatis: DEBUG
            
custom:
  property:
    jdbc:
      url: jdbcUrl-prod1

upload:
  base:
    path: /data001/mfs
      
wx:
  act:
    bargain:
      url: /pages/cutprice/cutprice2
    img:
      path: /AA/actImg/upload
      
