server:
  port: 8001
  error:
    include-exception: true
    
spring:
  datasource:
    url: jdbc:mysql://db.mysql.ci.sanduspace.com:3306/app_online_30?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: user_dep
    password: ?,iN%er(/8ZEr<*nNX11
  rabbitmq:
    host: 10.10.30.134
    port: 5672
    username: admin
    password: 123456abc
  zipkin:
    baseUrl: http://10.10.30.159:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  aop:
    auto: true
    
  redis:
    host: redislogin.ci.sanduspace.com
    port: 33436
    password: sanduspace

     
logging:
  level:
    root: INFO
    org.springframework: ERROR
    
feign:
  hystrix:
    enabled: false
               
custom:
  property:
    jdbc:
      url: jdbcUrl-prod1

