package org.sandu.cloud.oauth2;

import org.springframework.security.jwt.Jwt;
import org.springframework.security.jwt.JwtHelper;
import org.springframework.security.jwt.crypto.sign.RsaVerifier;

public class Test {

	public static void main(String[] args) {
		 // Jwt jwt = JwtHelper.decode("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhYWEiOiJhYWEiLCJiYmIiOiJiYmIiLCJ1c2VyX25hbWUiOiJ1c2VybmFtZSIsInNjb3BlIjpbImFwcCJdLCJleHAiOjE1NTQ5NjM2NzUsImp0aSI6ImMyNWYyNDRjLWM1YjYtNDFkYS1hN2JmLWQwMzBkNDcyZDQwNSIsImNsaWVudF9pZCI6IkNsaWVudElkIn0.vHG9-vzIJ6xPrz6oXPPt6Tdf1QytV5my0gfWgeHew6c");
		String jwtString = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiIxIiwidXNlcnBpYyI6bnVsbCwidXNlcl9uYW1lIjoiaXRjYXN0Iiwic2NvcGUiOlsiYXBwIl0sIm5hbWUiOiJ0ZXN0MDIiLCJ1dHlwZSI6IjEwMTAwMiIsImlkIjoiNDkiLCJleHAiOjE1MzgyNTI1NzIsImF1dGhvcml0aWVzIjpbInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfYmFzZSIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfZGVsIiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9saXN0IiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9wbGFuIiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZSIsImNvdXJzZV9maW5kX2xpc3QiLCJ4Y190ZWFjaG1hbmFnZXIiLCJ4Y190ZWFjaG1hbmFnZXJfY291cnNlX21hcmtldCIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfcHVibGlzaCIsImNvdXJzZV9waWNfbGlzdCIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfYWRkIl0sImp0aSI6IjZlNzlmODJiLWM4ODMtNDNlNS05NjJkLTVmMTYxNjg5YzgwYiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.BpiRZ3UswraDPTD-6iywnwcT-00iSPlxCxUSLjR9VLVoAM2kWT71FkiLIRFaLRkdODB57KD_Lm3gaM5ch_a02lJygsrAEozo7mcjYCbE4HKpL0jg_Vue_bARnFLvCeUPX9KACy1F5sD1Br1e-QZQMHBdtGQVS5K_yyBE1pwtyR_JIktdmDpsxcitEirjmdTlEBcr29AbgxcWFfnRJ0YCr71m2AMJU02SSphj9nvKFUFFLL6odaqne84Uvr2WjYi7vcUoZ73C2lkFrM4i3-DOCj6JDTJPKJuWs2Aizm3EEKl_WTO0S6MW19rBK4A6snw9uIe-6pmL7Bo5xQys2faeQg";
		Jwt jwt = JwtHelper.decode(jwtString);
		//拿到jwt令牌中自定义的内容
	        String claims = jwt.getClaims();
	        System.out.println(claims);
	}
}
