server:
  port: 10120
  
spring:
  application:
    name: sandu-cloud-config
    
  cloud:
    config:
      server:
        svn:
          uri:  https://svns.sanduspace.cn/svn/nork/sdplatform/config-center/tags/config-center-all-ci
          username: test
          password: dep1234
          default-label: ci
  profiles:
    active: subversion

  rabbitmq:
    host: 10.10.30.134
    port: 5672
    username: admin
    password: 123456abc
    
eureka:
  client:
    service-url:
      defaultZone: http://10.10.30.165:10100/eureka/,http://10.10.30.166:10100/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip:NoIp}:${server.port}
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh