package com.sandu.cloud.activity.bargain.exception;

public enum BargainBizExceptionCode {
	SD_ERR_BARGAIN_OPT_ERROR("SD_ERR_BARGAIN_OPT_ERROR","操作失败!"),
	SD_ERR_BARGAIN_NOT_EXIST("SD_ERR_BARGAIN_NOT_EXIST","活动不存在!"),
	SD_ERR_BARGAIN_TASK_NOT_EXIST("SD_ERR_BARGAIN_TASK_NOT_EXIST","任务不存在!"),
	SD_ERR_BARGAIN_TASK_NOT_FINISH("SD_ERR_BARGAIN_TASK_NOT_FINISH","任务未完成!"),
	SD_ERR_BARGAIN_NO_STOCK("SD_ERR_BARGAIN_NO_STOCK","无库存!"),
	SD_ERR_BARGAIN_BAD_USER("SD_ERR_BARGAIN_BAD_USER","非法用户!"),
	SD_ERR_BARGAIN_AWARD_REPEAT("SD_ERR_BARGAIN_AWARD_REPEAT","请不要重复领奖!"),
	SD_ERR_BARGAIN_BAD_OPT("SD_ERR_BARGAIN_BAD_OPT","非法操作!"),
	SD_ERR_BARGAIN_REPEAT_CUT("SD_ERR_BARGAIN_REPEAT_CUT","不能重复砍价!"),
	SD_ERR_BARGAIN_REPEAT_ONLY_NEW_USER("SD_ERR_BARGAIN_REPEAT_ONLY_NEW_USER","对不起,本活动仅限新用户帮忙砍价."),
	SD_ERR_BARGAIN_NO_CHANCE_TODAY("SD_ERR_BARGAIN_NO_CHANCE_TODAY","你今日的砍价机会已用完,明日再来帮TA砍价吧!"),
	SD_ERR_BARGAIN_NO_CHANCE("SD_ERR_BARGAIN_NO_CHANCE","你的砍价机会已用完!"),
	SD_ERR_BARGAIN_NO_CONFIG_CUT_FRIENDS("SD_ERR_BARGAIN_NO_CONFIG_CUT_FRIENDS","没有配置可帮砍价好友数量"),
	SD_ERR_BARGAIN_REG_COMPLETE("SD_ERR_BARGAIN_REG_COMPLETE","任务已完成!"),
	SD_ERR_BARGAIN_ENDED("SD_ERR_BARGAIN_ENDED","活动已结束!"),
	SD_ERR_BARGAIN_UNBEGIN("SD_ERR_BARGAIN_UNBEGIN","活动未开始!"),
	SD_ERR_BARGAIN_MOBILE_ERROR("SD_ERR_BARGAIN_MOBILE_ERROR","手机号格式有误!"),
	SD_ERR_BARGAIN_PARAM_NOT_NULL("SD_ERR_BARGAIN_PARAM_NOT_NULL","参数不能为空!"),
	SD_ERR_BARGAIN_BEGIN_DATE_FORMAT_ERROR("SD_ERR_BARGAIN_BEGIN_DATE_FORMAT_ERROR","开始时间格式不正确!"),
	SD_ERR_BARGAIN_END_DATE_FORMAT_ERROR("SD_ERR_BARGAIN_END_DATE_FORMAT_ERROR","结束时间格式不正确!"),
	SD_ERR_BARGAIN_END_DATE_MUST_AFTER_BEGIN_DATE("SD_ERR_BARGAIN_END_DATE_MUST_AFTER_BEGIN_DATE","开始时间不能小于结束时间!"),
	SD_ERR_BARGAIN_MY_CUT_PRICE_MAX_PRICE_MUST_BIGGER_THAN_MIN_PRICE("SD_ERR_BARGAIN_MY_CUT_PRICE_MAX_PRICE_MUST_BIGGER_THAN_MIN_PRICE","自己砍价最高金额不能低于自己砍价最小金额!"),
	SD_ERR_BARGAIN_CUT_PRICE_MAX_PRICE_MUST_BIGGER_THAN_MIN_PRICE("SD_ERR_BARGAIN_CUT_PRICE_MAX_PRICE_MUST_BIGGER_THAN_MIN_PRICE","好友砍价最高金额不能低于好友砍价最低金额!"),
	SD_ERR_BARGAIN_STOCK_CAN_NOT_BE_NULL("SD_ERR_BARGAIN_STOCK_CAN_NOT_BE_NULL","请添加活动的商品库存"),
	SD_ERR_BARGAIN_DISPLAY_STOCK_MUST_BIGGER_THAN_REAL_STOCK("SD_ERR_BARGAIN_DISPLAY_STOCK_MUST_BIGGER_THAN_REAL_STOCK","商品显示库存不得小于商品实际库存"),
	SD_ERR_BARGAIN_HELP_CUT_PER_DAY_MUST_NOT_BE_NULL("SD_ERR_BARGAIN_HELP_CUT_PER_DAY_MUST_NOT_BE_NULL","请输入每人可帮砍价好友数"),
	SD_ERR_BARGAIN_HELP_CUT_PER_ACT_MUST_NOT_BE_NULL("SD_ERR_BARGAIN_HELP_CUT_PER_ACT_MUST_NOT_BE_NULL","好友/整个活动期间必须大于0"),
	SD_ERR_BARGAIN_HELP_CUT_PER_DAY_MUST_NOT_BE_NULL2("SD_ERR_BARGAIN_HELP_CUT_PER_DAY_MUST_NOT_BE_NULL2","好友/每天必须大于0"),
	SD_ERR_BARGAIN_HAS_FINISH("SD_ERR_BARGAIN_HAS_FINISH","活动已经结束,不能更新数据!"),
	SD_ERR_BARGAIN_END_FIRST_BEFORE_DELETE("SD_ERR_BARGAIN_END_FIRST_BEFORE_DELETE","请先结束活动再删除!"),
	SD_ERR_BARGAIN_DECREASE_NUM_CAN_NOT_BIGGER_THAN_REMAIN_STOCK("SD_ERR_BARGAIN_DECREASE_NUM_CAN_NOT_BIGGER_THAN_REMAIN_STOCK","虚拟扣除参数 不能大于库存剩余数量"),
	
	SD_ERR_BARGAIN_UPLOAD_IMAGE_ERROR("SD_ERR_BARGAIN_UPLOAD_IMAGE_ERROR","上传图片异常!"),
	SD_ERR_BARGAIN_MINI_CONFIG_NOT_FOUND("SD_ERR_BARGAIN_MINI_CONFIG_NOT_FOUND","appid错误或者服务器未配置secret!"),
	SD_ERR_BARGAIN_MINI_TEMPLATE_MSG_NOT_FOUND("SD_ERR_BARGAIN_MINI_TEMPLATE_MSG_NOT_FOUND","未配置渲染模板消息!"),
	
	SD_ERR_BARGAIN_SMS_CODE_IS_NOT_EXIST("SD_ERR_BARGAIN_SMS_CODE_IS_NOT_EXIST","验证码不存在!"),
	SD_ERR_BARGAIN_SMS_CODE_ERROR("SD_ERR_BARGAIN_SMS_CODE_ERROR","验证码不正确!"),
	SD_ERR_BARGAIN_SMS_CODE_REPEAT_ERROR("SD_ERR_BARGAIN_SMS_CODE_REPEAT_ERROR","请勿重复发送!"),
	
	
	
	
	
	SD_ERR_BARGAIN_PARAM_ERROR("SD_ERR_BARGAIN_PARAM_ERROR","非法参数!");
	
	private String code;
	private String message;
	
	private BargainBizExceptionCode(String code,String message) {
		this.code = code;
		this.message = message;
	}
	
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	
	
	
}
