package com.sandu.cloud.pay.exception;

public enum PayExceptionCode {
	
	SD_ERR_PAY_METHOD_ERROR("SD_ERR_PAY_METHOD_ERROR","支付方式不正确!"),
	SD_ERR_PAY_REQUEST_EXPIRED_ERROR("SD_ERR_PAY_REQUEST_EXPIRED_ERROR","请求已过期!"),
	
	SD_ERR_PAY_WX_APP_CLIENT_NOT_FOUND("SD_ERR_PAY_WX_APP_CLIENT_NOT_FOUND","未找到客户端配置信息!"),
	SD_ERR_PAY_WX_PAY_CONFIG_NOT_FOUND("SD_ERR_PAY_WX_PAY_CONFIG_NOT_FOUND","未找到微信支付配置信息!"),
	SD_ERR_PAY_ALI_PAY_CONFIG_NOT_FOUND("SD_ERR_PAY_ALI_PAY_CONFIG_NOT_FOUND","未找到支付宝支付配置信息!"),
	SD_ERR_PAY_ALI_REFUND_REPEAT("SD_ERR_PAY_ALI_REFUND_REPEAT","订单已全额退款!"),
	SD_ERR_PAY_ALI_REFUND_ERROR("SD_ERR_PAY_ALI_REFUND_ERROR","支付宝退款异常!"),
	SD_ERR_PAY_ALI_WAIT_BUYER_PAY_ERROR("SD_ERR_PAY_ALI_WAIT_BUYER_PAY_ERROR","等待支付状态不处理回调!"),
	SD_ERR_PAY_ALI_APP_ERROR("SD_ERR_PAY_ALI_APP_ERROR","支付宝app支付异常!"),
	SD_ERR_PAY_ALI_H5_ERROR("SD_ERR_PAY_ALI_H5_ERROR","支付宝H5支付异常!"),
	SD_ERR_PAY_ALI_SCAN_CODE_ERROR("SD_ERR_PAY_ALI_SCAN_CODE_ERROR","支付宝扫码支付异常!"),
	SD_ERR_PAY_ORIGIN_TRADE_NOT_EXIST("SD_ERR_PAY_ORIGIN_TRADE_NOT_EXIST","原交易不存在!"),
	SD_ERR_PAY_WX_MINI_TRADE_RESULT_ERROR("SD_ERR_PAY_WX_MINI_TRADE_RESULT_ERROR","微信小程序下单结果异常!"),
	SD_ERR_PAY_WX_MINI_TRADE_ERROR("SD_ERR_PAY_WX_MINI_TRADE_ERROR","微信小程序支付下单异常!"),
	SD_ERR_PAY_WX_H5_TRADE_RESULT_ERROR("SD_ERR_PAY_WX_H5_TRADE_RESULT_ERROR","微信H5支付下单结果异常!"),
	SD_ERR_PAY_WX_H5_TRADE_ERROR("SD_ERR_PAY_WX_H5_TRADE_ERROR","微信H5支付下单异常!"),
	SD_ERR_PAY_WX_APP_TRADE_RESULT_ERROR("SD_ERR_PAY_WX_APP_TRADE_RESULT_ERROR","微信app支付下单结果异常!"),
	SD_ERR_PAY_WX_APP_TRADE_ERROR("SD_ERR_PAY_WX_APP_TRADE_ERROR","微信app支付下单异常!"),
	
	SD_ERR_PAY_WX_MINI_REFUND_ERROR("SD_ERR_PAY_WX_MINI_REFUND_ERROR","微信小程序退款异常!"),
	SD_ERR_PAY_WX_MINI_REFUND_RESULT_ERROR("SD_ERR_PAY_WX_MINI_REFUND_RESULT_ERROR","微信小程序退款结果异常!"),
	
	SD_ERR_PAY_WX_SCAN_CODE_REFUND_ERROR("SD_ERR_PAY_WX_SCAN_CODE_REFUND_ERROR","微信扫码退款异常!"),
	SD_ERR_PAY_WX_SCAN_CODE_REFUND_RESULT_ERROR("SD_ERR_PAY_WX_SCAN_CODE_REFUND_RESULT_ERROR","微信扫码退款结果异常!"),
	
	SD_ERR_PAY_TRADE_REPEAT_PROCESS_ERROR("SD_ERR_PAY_TRADE_REPEAT_PROCESS_ERROR","重复处理!"),
	SD_ERR_PAY_TRADE_NOT_EXIST("SD_ERR_PAY_TRADE_NOT_EXIST","交易不存在!"),
	SD_ERR_PAY_SIGN_ERROR("SD_ERR_PAY_SIGN_ERROR","签名错误!"),
	SD_ERR_PAY_TOTAL_FEE_ERROR("SD_ERR_PAY_TOTAL_FEE_ERROR","交易金额不正确!"),
	SD_ERR_PAY_ORIGIN_TRADE_NO_AND_PAY_NO_ARE_NULL("SD_ERR_PAY_ORIGIN_TRADE_NO_AND_PAY_NO_ARE_NULL","原交易号或原支付号不能同时为空"),
	SD_ERR_PAY_PARAM_ERROR("SD_ERR_PAY_PARAM_ERROR","非法参数!");
	
	
	private String code;
	private String message;
	
	private PayExceptionCode(String code,String message) {
		this.code = code;
		this.message = message;
	}
	
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	
	
	
}
