server:
  port: 8002
  error:
    include-exception: true  
      
spring:
  redis:
    host: redislogin.ci.sanduspace.com
    port: 33436
    password: sanduspace


feign:
  hystrix:
    enabled: false
          