server:
  port: 8080
  
spring:
  application:
    name: sandu-cloud-pay-service
  datasource:
    url: jdbc:mysql://db.mysql.ci.sanduspace.com:3306/app_online_30?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: user_dep
    password: ?,iN%er(/8ZEr<*nNX11
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  aop:
    auto: true      
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10100/eureka/

feign:
  hystrix:
    enabled: false

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 6000

# logging.file: d:/zz/z.log
# logging.file.max-size: 10MB
            
custom:
  property:
    jdbc:
      url: jdbcUrl-dev

